#!/usr/bin/env python3
"""Fix words.json: merge split multi-word entries and add correct IPA phonetics."""

import json
import re
import copy

# ============================================================
# IPA phonetics dictionary for KET-level English words
# ============================================================
IPA_DICT = {
    # Animals
    "animal": "ˈænɪml", "bear": "beə(r)", "bee": "biː", "bird": "bɜːd",
    "cat": "kæt", "chicken": "ˈtʃɪkɪn", "cow": "kaʊ", "crocodile": "ˈkrɒkədaɪl",
    "dog": "dɒɡ", "donkey": "ˈdɒŋki", "duck": "dʌk", "elephant": "ˈelɪfənt",
    "fish": "fɪʃ", "frog": "frɒɡ", "giraffe": "dʒɪˈrɑːf", "goat": "ɡəʊt",
    "hippo": "ˈhɪpəʊ", "horse": "hɔːs", "lizard": "ˈlɪzəd", "monkey": "ˈmʌŋki",
    "mouse/mice": "maʊs/maɪs", "pet": "pet", "sheep": "ʃiːp", "snake": "sneɪk",
    "spider": "ˈspaɪdə(r)", "tail": "teɪl", "tiger": "ˈtaɪɡə(r)", "zebra": "ˈzebrə",
    "zoo": "zuː", "bat": "bæt", "cage": "keɪdʒ", "dolphin": "ˈdɒlfɪn",
    "fly": "flaɪ", "jungle": "ˈdʒʌŋɡl", "kangaroo": "ˌkæŋɡəˈruː",
    "kitten": "ˈkɪtn", "lion": "ˈlaɪən", "panda": "ˈpændə", "parrot": "ˈpærət",
    "penguin": "ˈpeŋɡwɪn", "puppy": "ˈpʌpi", "rabbit": "ˈræbɪt", "shark": "ʃɑːk",
    "snail": "sneɪl", "whale": "weɪl", "beetle": "ˈbiːtl", "butterfly": "ˈbʌtəflaɪ",
    "camel": "ˈkæml", "creature": "ˈkriːtʃə(r)", "dinosaur": "ˈdaɪnəsɔː(r)",
    "eagle": "ˈiːɡl", "extinct": "ɪkˈstɪŋkt", "fur": "fɜː(r)", "insect": "ˈɪnsekt",
    "nest": "nest", "octopus": "ˈɒktəpəs", "swan": "swɒn", "tortoise": "ˈtɔːtəs",
    "wild": "waɪld", "wing": "wɪŋ",
    # Body & face
    "arm": "ɑːm", "body": "ˈbɒdi", "ear": "ɪə(r)", "eye": "aɪ", "face": "feɪs",
    "foot/feet": "fʊt/fiːt", "hair": "heə(r)", "hand": "hænd", "head": "hed",
    "leg": "leɡ", "mouth": "maʊθ", "nose": "nəʊz", "smile": "smaɪl",
    "back": "bæk", "beard": "bɪəd", "blond(e)": "blɒnd", "curly": "ˈkɜːli",
    "fair": "feə(r)", "fat": "fæt", "moustache": "məˈstɑːʃ", "neck": "nek",
    "shoulder": "ˈʃəʊldə(r)", "stomach": "ˈstʌmək", "thin": "θɪn",
    "straight": "streɪt", "tooth/teeth": "tuːθ/tiːθ", "elbow": "ˈelbəʊ",
    "finger": "ˈfɪŋɡə(r)", "knee": "niː", "toe": "təʊ",
    # Clothes
    "bag": "bæɡ", "boots": "buːts", "clothes": "kləʊðz", "dress": "dres",
    "glasses": "ˈɡlɑːsɪz", "handbag": "ˈhændbæɡ", "hat": "hæt",
    "jacket": "ˈdʒækɪt", "jeans": "dʒiːnz", "shirt": "ʃɜːt", "shoe": "ʃuː",
    "shorts": "ʃɔːts", "skirt": "skɜːt", "sock": "sɒk", "trousers": "ˈtraʊzəz",
    "T-shirt": "ˈtiːʃɜːt", "watch": "wɒtʃ", "wear": "weə(r)", "coat": "kəʊt",
    "helmet": "ˈhelmɪt", "scarf": "skɑːf", "sweater": "ˈswetə(r)",
    "swimsuit": "ˈswɪmsuːt", "belt": "belt", "bracelet": "ˈbreɪslət",
    "costume": "ˈkɒstjuːm", "crown": "kraʊn", "glove": "ɡlʌv",
    "necklace": "ˈnekləs", "pajamas": "pəˈdʒɑːməz", "pyjamas": "pəˈdʒɑːməz",
    "ring": "rɪŋ", "spot": "spɒt", "spotted": "ˈspɒtɪd", "stripe": "straɪp",
    "striped": "straɪpt", "sunglasses": "ˈsʌnɡlɑːsɪz", "trainers": "ˈtreɪnəz",
    "umbrella": "ʌmˈbrelə", "uniform": "ˈjuːnɪfɔːm",
    # Colours
    "black": "blæk", "blue": "bluː", "brown": "braʊn", "colour": "ˈkʌlə(r)",
    "color": "ˈkʌlə(r)", "gray": "ɡreɪ", "green": "ɡriːn", "grey": "ɡreɪ",
    "orange": "ˈɒrɪndʒ", "pink": "pɪŋk", "purple": "ˈpɜːpl", "red": "red",
    "white": "waɪt", "yellow": "ˈjeləʊ", "dark": "dɑːk", "light": "laɪt",
    "gold": "ɡəʊld", "silver": "ˈsɪlvə(r)",
    # Family & friends
    "aunt": "ɑːnt", "baby": "ˈbeɪbi", "boy": "bɔɪ", "brother": "ˈbrʌðə(r)",
    "child/children": "tʃaɪld/ˈtʃɪldrən", "cousin": "ˈkʌzn", "dad": "dæd",
    "daddy": "ˈdædi", "daughter": "ˈdɔːtə(r)", "family": "ˈfæməli",
    "father": "ˈfɑːðə(r)", "friend": "frend", "girl": "ɡɜːl",
    "granddaughter": "ˈɡrændɔːtə(r)", "grandfather": "ˈɡrænfɑːðə(r)",
    "grandma": "ˈɡrænmɑː", "grandmother": "ˈɡrænmʌðə(r)",
    "grandpa": "ˈɡrænpɑː", "grandparent": "ˈɡrænpeərənt",
    "grandson": "ˈɡrænsʌn", "man/men": "mæn/men", "mother": "ˈmʌðə(r)",
    "mum": "mʌm", "mummy": "ˈmʌmi", "parent": "ˈpeərənt", "people": "ˈpiːpl",
    "person": "ˈpɜːsn", "sister": "ˈsɪstə(r)", "son": "sʌn", "uncle": "ˈʌŋkl",
    "woman/women": "ˈwʊmən/ˈwɪmɪn", "child": "tʃaɪld", "children": "ˈtʃɪldrən",
    "man": "mæn", "men": "men", "woman": "ˈwʊmən", "women": "ˈwɪmɪn",
    "classmate": "ˈklɑːsmeɪt", "neighbour": "ˈneɪbə(r)", "neighbor": "ˈneɪbə(r)",
    "teenager": "ˈtiːneɪdʒə(r)", "adult": "ˈædʌlt", "guest": "ɡest",
    "husband": "ˈhʌzbənd", "wife": "waɪf", "king": "kɪŋ", "queen": "kwiːn",
    "prince": "prɪns", "princess": "prɪnˈses",
    # Food & drink
    "apple": "ˈæpl", "banana": "bəˈnɑːnə", "bean": "biːn", "biscuit": "ˈbɪskɪt",
    "bread": "bred", "breakfast": "ˈbrekfəst", "burger": "ˈbɜːɡə(r)",
    "cake": "keɪk", "candy": "ˈkændi", "carrot": "ˈkærət", "cheese": "tʃiːz",
    "chip": "tʃɪp", "chocolate": "ˈtʃɒklət", "coconut": "ˈkəʊkənʌt",
    "coffee": "ˈkɒfi", "cook": "kʊk", "dinner": "ˈdɪnə(r)", "drink": "drɪŋk",
    "eat": "iːt", "egg": "eɡ", "food": "fuːd", "fries": "fraɪz",
    "fruit": "fruːt", "grape": "ɡreɪp", "hungry": "ˈhʌŋɡri", "juice": "dʒuːs",
    "lemon": "ˈlemən", "lemonade": "ˌleməˈneɪd", "lunch": "lʌntʃ",
    "mango": "ˈmæŋɡəʊ", "meal": "miːl", "meat": "miːt", "milk": "mɪlk",
    "onion": "ˈʌnjən", "pasta": "ˈpæstə", "pea": "piː", "pear": "peə(r)",
    "pepper": "ˈpepə(r)", "picnic": "ˈpɪknɪk", "pie": "paɪ",
    "pineapple": "ˈpaɪnæpl", "pizza": "ˈpiːtsə", "potato": "pəˈteɪtəʊ",
    "rice": "raɪs", "salad": "ˈsæləd", "salt": "sɔːlt", "sandwich": "ˈsænwɪtʃ",
    "sausage": "ˈsɒsɪdʒ", "soup": "suːp", "sugar": "ˈʃʊɡə(r)", "tea": "tiː",
    "thirsty": "ˈθɜːsti", "toast": "təʊst", "tomato": "təˈmɑːtəʊ",
    "vegetable": "ˈvedʒtəbl", "water": "ˈwɔːtə(r)", "watermelon": "ˈwɔːtəmelən",
    "bottle": "ˈbɒtl", "bowl": "bəʊl", "cup": "kʌp", "flour": "ˈflaʊə(r)",
    "fork": "fɔːk", "glass": "ɡlɑːs", "knife": "naɪf", "menu": "ˈmenjuː",
    "mushroom": "ˈmʌʃruːm", "oil": "ɔɪl", "plate": "pleɪt", "recipe": "ˈresəpi",
    "snack": "snæk", "spoon": "spuːn", "strawberry": "ˈstrɔːbəri",
    "sweet": "swiːt", "waiter": "ˈweɪtə(r)", "waitress": "ˈweɪtrəs",
    "barbecue": "ˈbɑːbɪkjuː", "cereal": "ˈsɪəriəl", "cherry": "ˈtʃeri",
    "cream": "kriːm", "dessert": "dɪˈzɜːt", "freezer": "ˈfriːzə(r)",
    "fridge": "frɪdʒ", "grill": "ɡrɪl", "honey": "ˈhʌni", "jam": "dʒæm",
    "jug": "dʒʌɡ", "pan": "pæn", "peach": "piːtʃ", "pepper": "ˈpepə(r)",
    "sauce": "sɔːs", "seafood": "ˈsiːfuːd", "steak": "steɪk",
    "takeaway": "ˈteɪkəweɪ", "tin": "tɪn", "yoghurt": "ˈjɒɡət",
    # Health
    "cold": "kəʊld", "dentist": "ˈdentɪst", "doctor": "ˈdɒktə(r)",
    "earache": "ˈɪəreɪk", "fine": "faɪn", "headache": "ˈhedeɪk",
    "hospital": "ˈhɒspɪtl", "hurt": "hɜːt", "ill": "ɪl", "nurse": "nɜːs",
    "stomach ache": "ˈstʌmək eɪk", "temperature": "ˈtemprətʃə(r)",
    "tired": "ˈtaɪəd", "toothache": "ˈtuːθeɪk", "well": "wel",
    "ambulance": "ˈæmbjələns", "broken": "ˈbrəʊkən", "cough": "kɒf",
    "medicine": "ˈmedsn", "plaster": "ˈplɑːstə(r)", "sick": "sɪk",
    "accident": "ˈæksɪdənt", "bandage": "ˈbændɪdʒ", "chemist": "ˈkemɪst",
    "patient": "ˈpeɪʃnt", "prescription": "prɪˈskrɪpʃn",
    # The home
    "bath": "bɑːθ", "bathroom": "ˈbɑːθruːm", "bed": "bed",
    "bedroom": "ˈbedruːm", "bookcase": "ˈbʊkkeɪs", "chair": "tʃeə(r)",
    "clock": "klɒk", "computer": "kəmˈpjuːtə(r)", "cupboard": "ˈkʌbəd",
    "desk": "desk", "door": "dɔː(r)", "flat": "flæt", "floor": "flɔː(r)",
    "flower": "ˈflaʊə(r)", "garden": "ˈɡɑːdn", "hall": "hɔːl",
    "home": "həʊm", "house": "haʊs", "kitchen": "ˈkɪtʃɪn", "lamp": "læmp",
    "mirror": "ˈmɪrə(r)", "phone": "fəʊn", "picture": "ˈpɪktʃə(r)",
    "radio": "ˈreɪdiəʊ", "room": "ruːm", "shower": "ˈʃaʊə(r)",
    "sofa": "ˈsəʊfə", "table": "ˈteɪbl", "television": "ˈtelɪvɪʒn",
    "toilet": "ˈtɔɪlət", "toy": "tɔɪ", "tree": "triː", "TV": "ˌtiːˈviː",
    "wall": "wɔːl", "window": "ˈwɪndəʊ", "apartment": "əˈpɑːtmənt",
    "balcony": "ˈbælkəni", "blanket": "ˈblæŋkɪt", "carpet": "ˈkɑːpɪt",
    "ceiling": "ˈsiːlɪŋ", "drawer": "drɔː(r)", "fence": "fens",
    "furniture": "ˈfɜːnɪtʃə(r)", "garage": "ˈɡærɑːʒ", "gate": "ɡeɪt",
    "key": "kiː", "lift": "lɪft", "pillow": "ˈpɪləʊ", "roof": "ruːf",
    "shelf": "ʃelf", "stairs": "steəz", "towel": "ˈtaʊəl",
    "upstairs": "ˌʌpˈsteəz", "downstairs": "ˌdaʊnˈsteəz",
    "washing machine": "ˈwɒʃɪŋ məˈʃiːn", "air conditioning": "eə kənˈdɪʃnɪŋ",
    "alarm clock": "əˈlɑːm klɒk", "bin": "bɪn", "brush": "brʌʃ",
    "candle": "ˈkændl", "chimney": "ˈtʃɪmni", "curtain": "ˈkɜːtn",
    "entrance": "ˈentrəns", "exit": "ˈeksɪt", "fireplace": "ˈfaɪəpleɪs",
    "handle": "ˈhændl", "heating": "ˈhiːtɪŋ", "ladder": "ˈlædə(r)",
    "lock": "lɒk", "path": "pɑːθ", "plug": "plʌɡ", "step": "step",
    "switch": "swɪtʃ", "tap": "tæp", "vase": "vɑːz",
    # IT
    "app": "æp", "blog": "blɒɡ", "click": "klɪk", "email": "ˈiːmeɪl",
    "internet": "ˈɪntənet", "laptop": "ˈlæptɒp", "message": "ˈmesɪdʒ",
    "mouse": "maʊs", "online": "ˌɒnˈlaɪn", "password": "ˈpɑːswɜːd",
    "screen": "skriːn", "text": "tekst", "username": "ˈjuːzəneɪm",
    "video": "ˈvɪdiəʊ", "website": "ˈwebsaɪt", "webcam": "ˈwebkæm",
    "download": "ˌdaʊnˈləʊd", "keyboard": "ˈkiːbɔːd", "printer": "ˈprɪntə(r)",
    "program": "ˈprəʊɡræm", "search": "sɜːtʃ", "tablet": "ˈtæblət",
    "technology": "tekˈnɒlədʒi", "upload": "ˌʌpˈləʊd",
    # Materials
    "glass": "ɡlɑːs", "gold": "ɡəʊld", "metal": "ˈmetl", "paper": "ˈpeɪpə(r)",
    "plastic": "ˈplæstɪk", "silver": "ˈsɪlvə(r)", "wood": "wʊd",
    "cotton": "ˈkɒtn", "leather": "ˈleðə(r)", "rubber": "ˈrʌbə(r)",
    "stone": "stəʊn", "wool": "wʊl",
    # Numbers
    "zero": "ˈzɪərəʊ", "one": "wʌn", "two": "tuː", "three": "θriː",
    "four": "fɔː(r)", "five": "faɪv", "six": "sɪks", "seven": "ˈsevn",
    "eight": "eɪt", "nine": "naɪn", "ten": "ten", "eleven": "ɪˈlevn",
    "twelve": "twelv", "thirteen": "ˌθɜːˈtiːn", "fourteen": "ˌfɔːˈtiːn",
    "fifteen": "ˌfɪfˈtiːn", "sixteen": "ˌsɪksˈtiːn", "seventeen": "ˌsevnˈtiːn",
    "eighteen": "ˌeɪˈtiːn", "nineteen": "ˌnaɪnˈtiːn", "twenty": "ˈtwenti",
    "thirty": "ˈθɜːti", "forty": "ˈfɔːti", "fifty": "ˈfɪfti", "sixty": "ˈsɪksti",
    "seventy": "ˈsevnti", "eighty": "ˈeɪti", "ninety": "ˈnaɪnti",
    "hundred": "ˈhʌndrəd", "thousand": "ˈθaʊznd", "million": "ˈmɪljən",
    "first": "fɜːst", "second": "ˈsekənd", "third": "θɜːd",
    "number": "ˈnʌmbə(r)", "half": "hɑːf", "quarter": "ˈkwɔːtə(r)",
    "double": "ˈdʌbl", "pair": "peə(r)", "once": "wʌns", "twice": "twaɪs",
    # Places & directions
    "airport": "ˈeəpɔːt", "bank": "bæŋk", "beach": "biːtʃ",
    "bookshop": "ˈbʊkʃɒp", "bridge": "brɪdʒ", "café": "ˈkæfeɪ",
    "cinema": "ˈsɪnəmə", "city": "ˈsɪti", "country": "ˈkʌntri",
    "farm": "fɑːm", "hospital": "ˈhɒspɪtl", "hotel": "həʊˈtel",
    "library": "ˈlaɪbrəri", "map": "mæp", "market": "ˈmɑːkɪt",
    "museum": "mjuːˈziːəm", "park": "pɑːk", "playground": "ˈpleɪɡraʊnd",
    "restaurant": "ˈrestrɒnt", "road": "rəʊd", "school": "skuːl",
    "shop": "ʃɒp", "street": "striːt", "supermarket": "ˈsuːpəmɑːkɪt",
    "theatre": "ˈθɪətə(r)", "town": "taʊn", "village": "ˈvɪlɪdʒ",
    "left": "left", "right": "raɪt", "north": "nɔːθ", "south": "saʊθ",
    "east": "iːst", "west": "west", "corner": "ˈkɔːnə(r)",
    "crossing": "ˈkrɒsɪŋ", "direction": "dəˈrekʃn", "entrance": "ˈentrəns",
    "exit": "ˈeksɪt", "factory": "ˈfæktri", "field": "fiːld",
    "forest": "ˈfɒrɪst", "island": "ˈaɪlənd", "lake": "leɪk",
    "mountain": "ˈmaʊntɪn", "ocean": "ˈəʊʃn", "path": "pɑːθ",
    "river": "ˈrɪvə(r)", "sea": "siː", "station": "ˈsteɪʃn",
    "tower": "ˈtaʊə(r)", "waterfall": "ˈwɔːtəfɔːl",
    "castle": "ˈkɑːsl", "cave": "keɪv", "church": "tʃɜːtʃ",
    "desert": "ˈdezət", "harbour": "ˈhɑːbə(r)", "hill": "hɪl",
    "palace": "ˈpæləs", "port": "pɔːt", "pyramid": "ˈpɪrəmɪd",
    "statue": "ˈstætʃuː", "valley": "ˈvæli",
    # Prepositions
    "about": "əˈbaʊt", "above": "əˈbʌv", "after": "ˈɑːftə(r)",
    "at": "æt", "before": "bɪˈfɔː(r)", "behind": "bɪˈhaɪnd",
    "below": "bɪˈləʊ", "between": "bɪˈtwiːn", "by": "baɪ",
    "down": "daʊn", "for": "fɔː(r)", "from": "frɒm", "in": "ɪn",
    "inside": "ˌɪnˈsaɪd", "into": "ˈɪntə", "near": "nɪə(r)",
    "of": "ɒv", "off": "ɒf", "on": "ɒn", "opposite": "ˈɒpəzɪt",
    "out": "aʊt", "outside": "ˌaʊtˈsaɪd", "over": "ˈəʊvə(r)",
    "past": "pɑːst", "round": "raʊnd", "through": "θruː",
    "to": "tuː", "towards": "təˈwɔːdz", "under": "ˈʌndə(r)",
    "up": "ʌp", "with": "wɪð", "without": "wɪˈðaʊt",
    "across": "əˈkrɒs", "against": "əˈɡenst", "along": "əˈlɒŋ",
    "among": "əˈmʌŋ", "around": "əˈraʊnd", "during": "ˈdjʊərɪŋ",
    "except": "ɪkˈsept", "since": "sɪns", "until": "ənˈtɪl",
    # Pronouns
    "I": "aɪ", "you": "juː", "he": "hiː", "she": "ʃiː", "it": "ɪt",
    "we": "wiː", "they": "ðeɪ", "me": "miː", "him": "hɪm", "her": "hɜː(r)",
    "us": "ʌs", "them": "ðem", "my": "maɪ", "your": "jɔː(r)", "his": "hɪz",
    "its": "ɪts", "our": "ˈaʊə(r)", "their": "ðeə(r)", "mine": "maɪn",
    "yours": "jɔːz", "hers": "hɜːz", "ours": "ˈaʊəz", "theirs": "ðeəz",
    "this": "ðɪs", "that": "ðæt", "these": "ðiːz", "those": "ðəʊz",
    "myself": "maɪˈself", "yourself": "jɔːˈself", "himself": "hɪmˈself",
    "herself": "hɜːˈself", "itself": "ɪtˈself", "ourselves": "ɑːˈselvz",
    "themselves": "ðəmˈselvz", "who": "huː", "what": "wɒt", "which": "wɪtʃ",
    "whom": "huːm", "whose": "huːz", "somebody": "ˈsʌmbədi",
    "someone": "ˈsʌmwʌn", "something": "ˈsʌmθɪŋ", "anybody": "ˈenibɒdi",
    "anyone": "ˈeniwʌn", "anything": "ˈeniθɪŋ", "nobody": "ˈnəʊbədi",
    "nothing": "ˈnʌθɪŋ", "everybody": "ˈevribɒdi", "everyone": "ˈevriwʌn",
    "everything": "ˈevriθɪŋ", "each": "iːtʃ", "other": "ˈʌðə(r)",
    "another": "əˈnʌðə(r)",
    # Question words
    "how": "haʊ", "what": "wɒt", "when": "wen", "where": "weə(r)",
    "which": "wɪtʃ", "who": "huː", "whose": "huːz", "why": "waɪ",
    # Sports & leisure
    "ball": "bɔːl", "baseball": "ˈbeɪsbɔːl", "basketball": "ˈbɑːskɪtbɔːl",
    "bike": "baɪk", "boat": "bəʊt", "camera": "ˈkæmərə", "catch": "kætʃ",
    "climb": "klaɪm", "dance": "dɑːns", "draw": "drɔː", "drive": "draɪv",
    "fishing": "ˈfɪʃɪŋ", "fly": "flaɪ", "football": "ˈfʊtbɔːl",
    "game": "ɡeɪm", "guitar": "ɡɪˈtɑː(r)", "hobby": "ˈhɒbi",
    "hockey": "ˈhɒki", "jump": "dʒʌmp", "kick": "kɪk", "kite": "kaɪt",
    "movie": "ˈmuːvi", "music": "ˈmjuːzɪk", "paint": "peɪnt",
    "party": "ˈpɑːti", "photo": "ˈfəʊtəʊ", "piano": "piˈænəʊ",
    "play": "pleɪ", "present": "ˈpreznt", "race": "reɪs", "read": "riːd",
    "ride": "raɪd", "run": "rʌn", "sing": "sɪŋ", "skate": "skeɪt",
    "skateboard": "ˈskeɪtbɔːd", "ski": "skiː", "song": "sɒŋ",
    "sport": "spɔːt", "story": "ˈstɔːri", "swim": "swɪm",
    "tennis": "ˈtenɪs", "ticket": "ˈtɪkɪt", "walk": "wɔːk",
    "badminton": "ˈbædmɪntən", "band": "bænd", "bat": "bæt",
    "bowling": "ˈbəʊlɪŋ", "chess": "tʃes", "club": "klʌb",
    "competition": "ˌkɒmpəˈtɪʃn", "concert": "ˈkɒnsət", "drum": "drʌm",
    "exercise": "ˈeksəsaɪz", "fan": "fæn", "goal": "ɡəʊl",
    "golf": "ɡɒlf", "gym": "dʒɪm", "hit": "hɪt", "instrument": "ˈɪnstrəmənt",
    "match": "mætʃ", "member": "ˈmembə(r)", "net": "net",
    "player": "ˈpleɪə(r)", "point": "pɔɪnt", "pool": "puːl",
    "practice": "ˈpræktɪs", "prize": "praɪz", "puzzle": "ˈpʌzl",
    "score": "skɔː(r)", "show": "ʃəʊ", "stadium": "ˈsteɪdiəm",
    "surfing": "ˈsɜːfɪŋ", "team": "tiːm", "throw": "θrəʊ",
    "volleyball": "ˈvɒlibɔːl", "win": "wɪn", "yoga": "ˈjəʊɡə",
    "adventure": "ədˈventʃə(r)", "audience": "ˈɔːdiəns",
    "champion": "ˈtʃæmpiən", "circus": "ˈsɜːkəs", "coach": "kəʊtʃ",
    "comic": "ˈkɒmɪk", "entertainer": "ˌentəˈteɪnə(r)",
    "festival": "ˈfestɪvl", "magic": "ˈmædʒɪk", "marathon": "ˈmærəθən",
    "medal": "ˈmedl", "novel": "ˈnɒvl", "orchestra": "ˈɔːkɪstrə",
    "perform": "pəˈfɔːm", "performance": "pəˈfɔːməns",
    "poem": "ˈpəʊɪm", "recorder": "rɪˈkɔːdə(r)", "robot": "ˈrəʊbɒt",
    "sailing": "ˈseɪlɪŋ", "scene": "siːn", "stage": "steɪdʒ",
    "trumpet": "ˈtrʌmpɪt", "violin": "ˌvaɪəˈlɪn",
    # Nouns (general)
    "afternoon": "ˌɑːftəˈnuːn", "age": "eɪdʒ", "answer": "ˈɑːnsə(r)",
    "birthday": "ˈbɜːθdeɪ", "book": "bʊk", "box": "bɒks",
    "bus": "bʌs", "car": "kɑː(r)", "class": "klɑːs", "classroom": "ˈklɑːsruːm",
    "day": "deɪ", "end": "end", "evening": "ˈiːvnɪŋ", "example": "ɪɡˈzɑːmpl",
    "fun": "fʌn", "holiday": "ˈhɒlədeɪ", "homework": "ˈhəʊmwɜːk",
    "hour": "ˈaʊə(r)", "idea": "aɪˈdɪə", "job": "dʒɒb", "letter": "ˈletə(r)",
    "lesson": "ˈlesn", "line": "laɪn", "list": "lɪst", "lot": "lɒt",
    "minute": "ˈmɪnɪt", "money": "ˈmʌni", "morning": "ˈmɔːnɪŋ",
    "name": "neɪm", "news": "njuːz", "night": "naɪt", "page": "peɪdʒ",
    "part": "pɑːt", "pen": "pen", "pencil": "ˈpensl", "place": "pleɪs",
    "problem": "ˈprɒbləm", "question": "ˈkwestʃən", "rain": "reɪn",
    "sentence": "ˈsentəns", "side": "saɪd", "snow": "snəʊ",
    "star": "stɑː(r)", "sun": "sʌn", "test": "test", "thing": "θɪŋ",
    "time": "taɪm", "today": "təˈdeɪ", "tomorrow": "təˈmɒrəʊ",
    "tonight": "təˈnaɪt", "top": "tɒp", "trip": "trɪp", "turn": "tɜːn",
    "way": "weɪ", "week": "wiːk", "weekend": "ˌwiːkˈend", "word": "wɜːd",
    "work": "wɜːk", "world": "wɜːld", "year": "jɪə(r)", "yesterday": "ˈjestədeɪ",
    # Adjectives
    "afraid": "əˈfreɪd", "angry": "ˈæŋɡri", "bad": "bæd",
    "beautiful": "ˈbjuːtɪfl", "best": "best", "better": "ˈbetə(r)",
    "big": "bɪɡ", "boring": "ˈbɔːrɪŋ", "brave": "breɪv",
    "brilliant": "ˈbrɪliənt", "busy": "ˈbɪzi", "cheap": "tʃiːp",
    "clean": "kliːn", "clever": "ˈklevə(r)", "cool": "kuːl",
    "correct": "kəˈrekt", "crazy": "ˈkreɪzi", "dangerous": "ˈdeɪndʒərəs",
    "dear": "dɪə(r)", "different": "ˈdɪfrənt", "difficult": "ˈdɪfɪkəlt",
    "dirty": "ˈdɜːti", "dry": "draɪ", "easy": "ˈiːzi",
    "empty": "ˈempti", "excited": "ɪkˈsaɪtɪd", "exciting": "ɪkˈsaɪtɪŋ",
    "expensive": "ɪkˈspensɪv", "famous": "ˈfeɪməs", "fantastic": "fænˈtæstɪk",
    "fast": "fɑːst", "favourite": "ˈfeɪvərɪt", "free": "friː",
    "friendly": "ˈfrendli", "full": "fʊl", "funny": "ˈfʌni",
    "good": "ɡʊd", "great": "ɡreɪt", "happy": "ˈhæpi", "hard": "hɑːd",
    "heavy": "ˈhevi", "high": "haɪ", "horrible": "ˈhɒrəbl", "hot": "hɒt",
    "important": "ɪmˈpɔːtnt", "interesting": "ˈɪntrəstɪŋ", "kind": "kaɪnd",
    "large": "lɑːdʒ", "last": "lɑːst", "late": "leɪt", "little": "ˈlɪtl",
    "long": "lɒŋ", "loud": "laʊd", "lovely": "ˈlʌvli", "low": "ləʊ",
    "lucky": "ˈlʌki", "much": "mʌtʃ", "many": "ˈmeni", "more": "mɔː(r)",
    "most": "məʊst", "new": "njuː", "next": "nekst", "nice": "naɪs",
    "noisy": "ˈnɔɪzi", "old": "əʊld", "only": "ˈəʊnli", "open": "ˈəʊpən",
    "own": "əʊn", "perfect": "ˈpɜːfɪkt", "poor": "pɔː(r)",
    "popular": "ˈpɒpjələ(r)", "pretty": "ˈprɪti", "quiet": "ˈkwaɪət",
    "ready": "ˈredi", "real": "rɪəl", "rich": "rɪtʃ", "sad": "sæd",
    "safe": "seɪf", "same": "seɪm", "scared": "skeəd", "short": "ʃɔːt",
    "slow": "sləʊ", "small": "smɔːl", "sorry": "ˈsɒri", "special": "ˈspeʃl",
    "strong": "strɒŋ", "stupid": "ˈstjuːpɪd", "sure": "ʃʊə(r)",
    "surprised": "səˈpraɪzd", "sweet": "swiːt", "tall": "tɔːl",
    "terrible": "ˈterəbl", "thirsty": "ˈθɜːsti", "ugly": "ˈʌɡli",
    "warm": "wɔːm", "weak": "wiːk", "wet": "wet", "whole": "həʊl",
    "wide": "waɪd", "wonderful": "ˈwʌndəfl", "worried": "ˈwʌrid",
    "worse": "wɜːs", "worst": "wɜːst", "wrong": "rɒŋ", "young": "jʌŋ",
    "alive": "əˈlaɪv", "asleep": "əˈsliːp", "awake": "əˈweɪk",
    "awful": "ˈɔːfl", "bright": "braɪt", "careful": "ˈkeəfl",
    "comfortable": "ˈkʌmftəbl", "common": "ˈkɒmən", "deep": "diːp",
    "delicious": "dɪˈlɪʃəs", "enormous": "ɪˈnɔːməs", "fair": "feə(r)",
    "flat": "flæt", "fresh": "freʃ", "gentle": "ˈdʒentl",
    "huge": "hjuːdʒ", "impossible": "ɪmˈpɒsəbl", "international": "ˌɪntəˈnæʃnəl",
    "main": "meɪn", "narrow": "ˈnærəʊ", "natural": "ˈnætʃrəl",
    "necessary": "ˈnesəsəri", "normal": "ˈnɔːml", "possible": "ˈpɒsəbl",
    "private": "ˈpraɪvət", "proud": "praʊd", "round": "raʊnd",
    "rude": "ruːd", "serious": "ˈsɪəriəs", "sharp": "ʃɑːp",
    "silly": "ˈsɪli", "simple": "ˈsɪmpl", "soft": "sɒft",
    "strange": "streɪndʒ", "stupid": "ˈstjuːpɪd", "thick": "θɪk",
    "tiny": "ˈtaɪni", "traditional": "trəˈdɪʃənl", "true": "truː",
    "typical": "ˈtɪpɪkl", "unusual": "ʌnˈjuːʒuəl", "useful": "ˈjuːsfl",
    # Verbs - regular
    "answer": "ˈɑːnsə(r)", "arrive": "əˈraɪv", "ask": "ɑːsk",
    "call": "kɔːl", "carry": "ˈkæri", "change": "tʃeɪndʒ",
    "clean": "kliːn", "climb": "klaɪm", "close": "kləʊz",
    "cook": "kʊk", "copy": "ˈkɒpi", "count": "kaʊnt", "cross": "krɒs",
    "cry": "kraɪ", "dance": "dɑːns", "decide": "dɪˈsaɪd",
    "enjoy": "ɪnˈdʒɔɪ", "explain": "ɪkˈspleɪn", "finish": "ˈfɪnɪʃ",
    "follow": "ˈfɒləʊ", "guess": "ɡes", "happen": "ˈhæpən",
    "hate": "heɪt", "help": "help", "hope": "həʊp", "hurry": "ˈhʌri",
    "invite": "ɪnˈvaɪt", "join": "dʒɔɪn", "laugh": "lɑːf",
    "learn": "lɜːn", "like": "laɪk", "listen": "ˈlɪsn", "live": "lɪv",
    "look": "lʊk", "love": "lʌv", "move": "muːv", "need": "niːd",
    "open": "ˈəʊpən", "order": "ˈɔːdə(r)", "paint": "peɪnt",
    "phone": "fəʊn", "plan": "plæn", "play": "pleɪ", "point": "pɔɪnt",
    "practice": "ˈpræktɪs", "prefer": "prɪˈfɜː(r)", "pull": "pʊl",
    "push": "pʊʃ", "rain": "reɪn", "remember": "rɪˈmembə(r)",
    "return": "rɪˈtɜːn", "save": "seɪv", "shout": "ʃaʊt",
    "show": "ʃəʊ", "smile": "smaɪl", "snow": "snəʊ", "spell": "spel",
    "start": "stɑːt", "stay": "steɪ", "stop": "stɒp", "study": "ˈstʌdi",
    "talk": "tɔːk", "taste": "teɪst", "thank": "θæŋk", "touch": "tʌtʃ",
    "travel": "ˈtrævl", "try": "traɪ", "turn": "tɜːn", "use": "juːz",
    "visit": "ˈvɪzɪt", "wait": "weɪt", "walk": "wɔːk", "want": "wɒnt",
    "wash": "wɒʃ", "watch": "wɒtʃ", "work": "wɜːk", "worry": "ˈwʌri",
    "add": "æd", "agree": "əˈɡriː", "appear": "əˈpɪə(r)",
    "believe": "bɪˈliːv", "belong": "bɪˈlɒŋ", "borrow": "ˈbɒrəʊ",
    "check": "tʃek", "collect": "kəˈlekt", "compare": "kəmˈpeə(r)",
    "complete": "kəmˈpliːt", "continue": "kənˈtɪnjuː", "correct": "kəˈrekt",
    "cover": "ˈkʌvə(r)", "deliver": "dɪˈlɪvə(r)", "describe": "dɪˈskraɪb",
    "design": "dɪˈzaɪn", "develop": "dɪˈveləp", "die": "daɪ",
    "disappear": "ˌdɪsəˈpɪə(r)", "discover": "dɪˈskʌvə(r)",
    "discuss": "dɪˈskʌs", "dream": "driːm", "drop": "drɒp",
    "enter": "ˈentə(r)", "escape": "ɪˈskeɪp", "expect": "ɪkˈspekt",
    "experience": "ɪkˈspɪəriəns", "fail": "feɪl", "fill": "fɪl",
    "fix": "fɪks", "frighten": "ˈfraɪtn", "hurry": "ˈhʌri",
    "imagine": "ɪˈmædʒɪn", "improve": "ɪmˈpruːv", "include": "ɪnˈkluːd",
    "increase": "ɪnˈkriːs", "introduce": "ˌɪntrəˈdjuːs",
    "invent": "ɪnˈvent", "land": "lænd", "last": "lɑːst",
    "lend": "lend", "lie": "laɪ", "lift": "lɪft", "manage": "ˈmænɪdʒ",
    "mark": "mɑːk", "matter": "ˈmætə(r)", "mean": "miːn",
    "measure": "ˈmeʒə(r)", "mention": "ˈmenʃn", "mind": "maɪnd",
    "miss": "mɪs", "mix": "mɪks", "notice": "ˈnəʊtɪs",
    "offer": "ˈɒfə(r)", "own": "əʊn", "pack": "pæk", "pass": "pɑːs",
    "pay": "peɪ", "pick": "pɪk", "place": "pleɪs", "prepare": "prɪˈpeə(r)",
    "produce": "prəˈdjuːs", "promise": "ˈprɒmɪs", "protect": "prəˈtekt",
    "provide": "prəˈvaɪd", "reach": "riːtʃ", "receive": "rɪˈsiːv",
    "record": "rɪˈkɔːd", "recycle": "ˌriːˈsaɪkl", "relax": "rɪˈlæks",
    "repair": "rɪˈpeə(r)", "repeat": "rɪˈpiːt", "replace": "rɪˈpleɪs",
    "rest": "rest", "seem": "siːm", "sell": "sel", "send": "send",
    "share": "ʃeə(r)", "smell": "smel", "suggest": "səˈdʒest",
    "suppose": "səˈpəʊz", "surprise": "səˈpraɪz", "teach": "tiːtʃ",
    "test": "test", "tidy": "ˈtaɪdi", "train": "treɪn",
    "translate": "trænzˈleɪt", "type": "taɪp", "understand": "ˌʌndəˈstænd",
    "wake": "weɪk", "warn": "wɔːn", "weigh": "weɪ", "wish": "wɪʃ",
    "wonder": "ˈwʌndə(r)",
    # Verbs - irregular
    "be": "biː", "become": "bɪˈkʌm", "begin": "bɪˈɡɪn",
    "break": "breɪk", "bring": "brɪŋ", "build": "bɪld", "buy": "baɪ",
    "can": "kæn", "catch": "kætʃ", "choose": "tʃuːz", "come": "kʌm",
    "cost": "kɒst", "cut": "kʌt", "do": "duː", "draw": "drɔː",
    "drink": "drɪŋk", "drive": "draɪv", "eat": "iːt", "fall": "fɔːl",
    "feel": "fiːl", "find": "faɪnd", "fly": "flaɪ", "forget": "fəˈɡet",
    "get": "ɡet", "give": "ɡɪv", "go": "ɡəʊ", "grow": "ɡrəʊ",
    "have": "hæv", "hear": "hɪə(r)", "hide": "haɪd", "hold": "həʊld",
    "keep": "kiːp", "know": "nəʊ", "leave": "liːv", "let": "let",
    "lose": "luːz", "make": "meɪk", "meet": "miːt", "must": "mʌst",
    "put": "pʊt", "read": "riːd", "ride": "raɪd", "ring": "rɪŋ",
    "run": "rʌn", "say": "seɪ", "see": "siː", "sell": "sel",
    "send": "send", "set": "set", "shall": "ʃæl", "should": "ʃʊd",
    "shut": "ʃʌt", "sing": "sɪŋ", "sit": "sɪt", "sleep": "sliːp",
    "speak": "spiːk", "spend": "spend", "stand": "stænd",
    "steal": "stiːl", "swim": "swɪm", "take": "teɪk", "tell": "tel",
    "think": "θɪŋk", "throw": "θrəʊ", "wake": "weɪk", "wear": "weə(r)",
    "will": "wɪl", "win": "wɪn", "write": "raɪt", "would": "wʊd",
    "could": "kʊd", "might": "maɪt",
    # Adverbs
    "again": "əˈɡen", "also": "ˈɔːlsəʊ", "always": "ˈɔːlweɪz",
    "away": "əˈweɪ", "enough": "ɪˈnʌf", "ever": "ˈevə(r)",
    "here": "hɪə(r)", "just": "dʒʌst", "never": "ˈnevə(r)",
    "not": "nɒt", "now": "naʊ", "often": "ˈɒfn", "only": "ˈəʊnli",
    "perhaps": "pəˈhæps", "quite": "kwaɪt", "really": "ˈrɪəli",
    "sometimes": "ˈsʌmtaɪmz", "soon": "suːn", "still": "stɪl",
    "then": "ðen", "there": "ðeə(r)", "today": "təˈdeɪ",
    "together": "təˈɡeðə(r)", "too": "tuː", "usually": "ˈjuːʒuəli",
    "very": "ˈveri", "well": "wel", "already": "ɔːlˈredi",
    "almost": "ˈɔːlməʊst", "certainly": "ˈsɜːtnli",
    "especially": "ɪˈspeʃəli", "exactly": "ɪɡˈzæktli",
    "finally": "ˈfaɪnəli", "however": "haʊˈevə(r)",
    "immediately": "ɪˈmiːdiətli", "instead": "ɪnˈsted",
    "luckily": "ˈlʌkɪli", "mainly": "ˈmeɪnli", "nearly": "ˈnɪəli",
    "probably": "ˈprɒbəbli", "recently": "ˈriːsntli",
    "slowly": "ˈsləʊli", "suddenly": "ˈsʌdnli",
    "unfortunately": "ʌnˈfɔːtʃənətli",
    # Conjunctions
    "and": "ænd", "but": "bʌt", "or": "ɔː(r)", "because": "bɪˈkɒz",
    "so": "səʊ", "if": "ɪf", "when": "wen", "while": "waɪl",
    "than": "ðæn", "that": "ðæt", "although": "ɔːlˈðəʊ",
    "since": "sɪns", "unless": "ənˈles", "until": "ənˈtɪl",
    "whether": "ˈweðə(r)",
    # Determiners
    "a": "ə", "an": "ən", "the": "ðə", "some": "sʌm", "any": "ˈeni",
    "no": "nəʊ", "every": "ˈevri", "all": "ɔːl", "both": "bəʊθ",
    "few": "fjuː", "little": "ˈlɪtl", "many": "ˈmeni", "much": "mʌtʃ",
    "several": "ˈsevrəl", "enough": "ɪˈnʌf",
    # Modals
    "can": "kæn", "could": "kʊd", "may": "meɪ", "might": "maɪt",
    "must": "mʌst", "shall": "ʃæl", "should": "ʃʊd", "will": "wɪl",
    "would": "wʊd",
    # Exclamations
    "hello": "həˈləʊ", "hi": "haɪ", "goodbye": "ˌɡʊdˈbaɪ",
    "bye": "baɪ", "please": "pliːz", "sorry": "ˈsɒri",
    "yes": "jes", "no": "nəʊ", "OK": "ˌəʊˈkeɪ", "oh": "əʊ",
    "wow": "waʊ", "oops": "ʊps", "ouch": "aʊtʃ",
    "congratulations": "kənˌɡrætʃuˈleɪʃnz", "welcome": "ˈwelkəm",
    # Transport & travel
    "bicycle": "ˈbaɪsɪkl", "boat": "bəʊt", "bus": "bʌs", "car": "kɑː(r)",
    "helicopter": "ˈhelɪkɒptə(r)", "lorry": "ˈlɒri", "motorbike": "ˈməʊtəbaɪk",
    "motorcycle": "ˈməʊtəsaɪkl", "plane": "pleɪn", "ship": "ʃɪp",
    "taxi": "ˈtæksi", "ticket": "ˈtɪkɪt", "train": "treɪn",
    "tram": "træm", "truck": "trʌk", "van": "væn",
    "passenger": "ˈpæsɪndʒə(r)", "petrol": "ˈpetrəl", "platform": "ˈplætfɔːm",
    "railway": "ˈreɪlweɪ", "seat": "siːt", "suitcase": "ˈsuːtkeɪs",
    "wheel": "wiːl", "journey": "ˈdʒɜːni", "luggage": "ˈlʌɡɪdʒ",
    "passport": "ˈpɑːspɔːt", "tourist": "ˈtʊərɪst", "traffic": "ˈtræfɪk",
    "flight": "flaɪt", "fuel": "ˈfjuːəl", "garage": "ˈɡærɑːʒ",
    "motorway": "ˈməʊtəweɪ", "parking": "ˈpɑːkɪŋ", "pilot": "ˈpaɪlət",
    "tyre": "ˈtaɪə(r)",
    # School & education
    "board": "bɔːd", "chalk": "tʃɔːk", "dictionary": "ˈdɪkʃənri",
    "eraser": "ɪˈreɪzə(r)", "exam": "ɪɡˈzæm", "geography": "dʒiˈɒɡrəfi",
    "history": "ˈhɪstri", "language": "ˈlæŋɡwɪdʒ", "math": "mæθ",
    "maths": "mæθs", "notebook": "ˈnəʊtbʊk", "project": "ˈprɒdʒekt",
    "rubber": "ˈrʌbə(r)", "ruler": "ˈruːlə(r)", "science": "ˈsaɪəns",
    "student": "ˈstjuːdnt", "subject": "ˈsʌbdʒɪkt", "teacher": "ˈtiːtʃə(r)",
    "university": "ˌjuːnɪˈvɜːsəti",
    # Weather
    "cloud": "klaʊd", "cloudy": "ˈklaʊdi", "fog": "fɒɡ", "foggy": "ˈfɒɡi",
    "ice": "aɪs", "rainy": "ˈreɪni", "snowy": "ˈsnəʊi", "storm": "stɔːm",
    "sunny": "ˈsʌni", "temperature": "ˈtemprətʃə(r)", "weather": "ˈweðə(r)",
    "wind": "wɪnd", "windy": "ˈwɪndi", "degree": "dɪˈɡriː",
    "lightning": "ˈlaɪtnɪŋ", "thunder": "ˈθʌndə(r)",
    # Work & jobs
    "actor": "ˈæktə(r)", "artist": "ˈɑːtɪst", "businessman": "ˈbɪznəsmæn",
    "businesswoman": "ˈbɪznəswʊmən", "clown": "klaʊn",
    "cook": "kʊk", "dentist": "ˈdentɪst", "doctor": "ˈdɒktə(r)",
    "driver": "ˈdraɪvə(r)", "engineer": "ˌendʒɪˈnɪə(r)",
    "farmer": "ˈfɑːmə(r)", "firefighter": "ˈfaɪəfaɪtə(r)",
    "journalist": "ˈdʒɜːnəlɪst", "manager": "ˈmænɪdʒə(r)",
    "mechanic": "məˈkænɪk", "musician": "mjuˈzɪʃn",
    "nurse": "nɜːs", "photographer": "fəˈtɒɡrəfə(r)",
    "pilot": "ˈpaɪlət", "police officer": "pəˈliːs ˈɒfɪsə(r)",
    "scientist": "ˈsaɪəntɪst", "secretary": "ˈsekrətri",
    "singer": "ˈsɪŋə(r)", "soldier": "ˈsəʊldʒə(r)",
    "waiter": "ˈweɪtə(r)", "waitress": "ˈweɪtrəs",
    "writer": "ˈraɪtə(r)",
    # Misc common words
    "also": "ˈɔːlsəʊ", "very": "ˈveri", "really": "ˈrɪəli",
    "quite": "kwaɪt", "just": "dʒʌst", "still": "stɪl",
    "already": "ɔːlˈredi", "yet": "jet", "ago": "əˈɡəʊ",
    "since": "sɪns", "during": "ˈdjʊərɪŋ", "while": "waɪl",
    "before": "bɪˈfɔː(r)", "after": "ˈɑːftə(r)", "until": "ənˈtɪl",
    "above": "əˈbʌv", "below": "bɪˈləʊ", "between": "bɪˈtwiːn",
    "among": "əˈmʌŋ", "through": "θruː", "across": "əˈkrɒs",
    "along": "əˈlɒŋ", "around": "əˈraʊnd", "towards": "təˈwɔːdz",
    "against": "əˈɡenst", "except": "ɪkˈsept",
    # Names (common ones in KET)
    "Monday": "ˈmʌndeɪ", "Tuesday": "ˈtjuːzdeɪ", "Wednesday": "ˈwenzdeɪ",
    "Thursday": "ˈθɜːzdeɪ", "Friday": "ˈfraɪdeɪ", "Saturday": "ˈsætədeɪ",
    "Sunday": "ˈsʌndeɪ", "January": "ˈdʒænjuəri", "February": "ˈfebruəri",
    "March": "mɑːtʃ", "April": "ˈeɪprəl", "May": "meɪ", "June": "dʒuːn",
    "July": "dʒuˈlaɪ", "August": "ˈɔːɡəst", "September": "sepˈtembə(r)",
    "October": "ɒkˈtəʊbə(r)", "November": "nəʊˈvembə(r)",
    "December": "dɪˈsembə(r)",
    # Extra words that might appear
    "x-ray": "ˈeks reɪ", "don't": "dəʊnt", "you're": "jɔː(r)",
    "o'clock": "əˈklɒk", "lots": "lɒts", "roller": "ˈrəʊlə(r)",
    "pop": "pɒp", "rock": "rɒk", "comic": "ˈkɒmɪk",
    "dining": "ˈdaɪnɪŋ", "living": "ˈlɪvɪŋ", "shopping": "ˈʃɒpɪŋ",
    "swimming": "ˈswɪmɪŋ", "police": "pəˈliːs", "post": "pəʊst",
    "fire": "ˈfaɪə(r)", "sports": "spɔːts", "board": "bɔːd",
    "polar": "ˈpəʊlə(r)", "baseball": "ˈbeɪsbɔːl",
    "city": "ˈsɪti", "town": "taʊn",
    "city/town": "ˈsɪti/taʊn", "town/city": "taʊn/ˈsɪti",
    "colour/color": "ˈkʌlə(r)",
    "grey/gray": "ɡreɪ",
    "favourite/favorite": "ˈfeɪvərɪt",
    "centre": "ˈsentə(r)", "center": "ˈsentə(r)",
    "neighbour/neighbor": "ˈneɪbə(r)",
    "theatre/theater": "ˈθɪətə(r)",
    "programme/program": "ˈprəʊɡræm",
    "practise": "ˈpræktɪs",
    "travelling": "ˈtrævəlɪŋ",
    "favourite": "ˈfeɪvərɪt",
    "favourite/favorite": "ˈfeɪvərɪt",
    "mum/mom": "mʌm/mɒm",
    "candy": "ˈkændi",
    "cookie": "ˈkʊki",
    "movie": "ˈmuːvi",
    "vacation": "vəˈkeɪʃn",
    "airplane": "ˈeəpleɪn",
    "apartment": "əˈpɑːtmənt",
    "elevator": "ˈelɪveɪtə(r)",
    "soccer": "ˈsɒkə(r)",
    "math": "mæθ",
    "store": "stɔː(r)",
    "trash": "træʃ",
    "movie theater": "ˈmuːvi ˈθɪətə(r)",
}


# ============================================================
# Multi-word merge rules: id -> (correct_word, correct_meaning)
# For entries where the word was split across word/meaning fields
# ============================================================
MERGE_FIXES = {
    23: ("polar bear", "北极熊"),
    93: ("baseball cap", "棒球帽"),
    200: ("candy", "糖果"),  # (UK sweet(s)) -> just candy
    215: ("ice cream", "冰淇淋"),
    304: ("fall over", "摔倒"),
    336: ("dining room", "餐厅"),
    347: ("living room", "客厅"),
    395: ("open/close a file", "打开/关闭文件"),
    475: ("in front of", "在…前面"),
    476: ("next to", "在…旁边"),
    489: ("bus station", "公交车站"),
    490: ("bus stop", "公交站"),
    491: ("car park", "停车场"),
    495: ("city/town centre", "市中心"),
    506: ("shopping centre", "购物中心"),
    507: ("sports centre", "体育中心"),
    512: ("swimming pool", "游泳池"),
    513: ("town/city centre", "市中心"),
    525: ("fire station", "消防站"),
    527: ("get to", "到达"),
    537: ("police station", "警察局"),
    538: ("post office", "邮局"),
    544: ("straight on", "直走"),
    682: ("comic book", "漫画书"),
    689: ("go shopping", "去购物"),
    693: ("ice skates", "冰鞋"),
    694: ("ice skating", "滑冰"),
    704: ("roller skates", "轮滑鞋"),
    705: ("roller skating", "轮滑"),
    710: ("sports centre", "体育中心"),
    712: ("swimming pool", "游泳池"),
    735: ("pop music", "流行音乐"),
    741: ("rock music", "摇滚音乐"),
    763: ("table tennis", "乒乓球"),
    764: ("take a photo", "拍照"),
    767: ("tennis racket", "网球拍"),
    809: ("Days of the week", "星期（总称）"),
    831: ("how long", "多久"),
    846: ("Months of the year", "月份（总称）"),
    864: ("board game", "棋类游戏"),
    890: ("bus station", "公交车站"),
    891: ("bus stop", "公交站"),
    899: ("fire engine", "消防车"),
    957: ("pop star", "流行明星"),
    969: ("fire engine", "消防车"),
    970: ("firefighter", "消防员"),
}
MERGE_FIXES.update({
    981: ("police officer", "警察"),
    982: ("police station", "警察局"),
    988: ("The world around us", "我们周围的世界"),
    1089: ("look at", "看"),
    1092: ("pick up", "捡起"),
    1105: ("dress up", "装扮"),
    1112: ("look for", "寻找"),
    1134: ("win a competition", "赢得比赛"),
    1148: ("look after", "照顾"),
    1149: ("look like", "看起来像"),
    1167: ("turn off", "关掉"),
    1168: ("turn on", "打开"),
    1181: ("go to bed", "去睡觉"),
    1182: ("go to sleep", "去睡觉"),
    1184: ("have got", "有"),
    1191: ("would like", "想要"),
    1192: ("be called", "被叫做"),
    1197: ("catch (a bus)", "赶（公交）"),
    1199: ("get dressed", "穿好衣服"),
    1200: ("get off", "下车"),
    1201: ("get on", "上车"),
    1202: ("get undressed", "脱衣服"),
    1203: ("get up", "起床"),
    1210: ("put on", "穿上"),
    1213: ("take off", "脱下（衣服）"),
    1221: ("find out", "找出"),
    1223: ("go out", "出去"),
    1229: ("make sure", "确保"),
    1236: ("don't worry", "别担心"),
    1243: ("oh dear", "天哪"),
    1244: ("See you!", "再见！"),
    1248: ("Come on!", "加油！"),
    1251: ("Go away!", "走开！"),
    1252: ("If you want!", "随你便！"),
    1253: ("In a minute!", "马上！"),
    1254: ("No problem!", "没问题！"),
    1255: ("you're welcome", "不客气"),
    1307: ("all right", "好吧"),
    1451: ("a lot of", "许多"),
    1452: ("lots of", "许多"),
    1469: ("a little", "一点"),
    1470: ("a few", "几个"),
    1475: ("a lot", "很多"),
    1490: ("all right", "好吧"),
    1501: ("a little", "一点"),
    1510: ("at the moment", "此刻"),
    1513: ("how much", "多少"),
    1514: ("how often", "多久一次"),
    1545: ("by myself", "独自"),
    1546: ("by yourself", "你自己"),
    1554: ("how long", "多久"),
    1562: ("of course", "当然"),
    1571: ("straight on", "直走"),
    1585: ("in front of", "在…前面"),
    1587: ("next to", "在…旁边"),
    1608: ("out of", "从…出来"),
    1633: ("a lot", "很多"),
    1690: ("how many", "多少（可数）"),
    1691: ("how old", "多大"),
    1698: ("how much", "多少（不可数）"),
    1699: ("how often", "多久一次"),
    1702: ("how long", "多久"),
})


# ============================================================
# IPA for multi-word phrases
# ============================================================
PHRASE_IPA = {
    "polar bear": "ˈpəʊlə beə(r)",
    "baseball cap": "ˈbeɪsbɔːl kæp",
    "ice cream": "ˌaɪs ˈkriːm",
    "fall over": "fɔːl ˈəʊvə(r)",
    "dining room": "ˈdaɪnɪŋ ruːm",
    "living room": "ˈlɪvɪŋ ruːm",
    "in front of": "ɪn frʌnt ɒv",
    "next to": "nekst tuː",
    "bus station": "bʌs ˈsteɪʃn",
    "bus stop": "bʌs stɒp",
    "car park": "kɑː pɑːk",
    "city/town centre": "ˈsɪti/taʊn ˈsentə(r)",
    "shopping centre": "ˈʃɒpɪŋ ˈsentə(r)",
    "sports centre": "spɔːts ˈsentə(r)",
    "swimming pool": "ˈswɪmɪŋ puːl",
    "town/city centre": "taʊn/ˈsɪti ˈsentə(r)",
    "fire station": "ˈfaɪə ˈsteɪʃn",
    "get to": "ɡet tuː",
    "police station": "pəˈliːs ˈsteɪʃn",
    "post office": "pəʊst ˈɒfɪs",
    "straight on": "streɪt ɒn",
    "comic book": "ˈkɒmɪk bʊk",
    "go shopping": "ɡəʊ ˈʃɒpɪŋ",
    "ice skates": "aɪs skeɪts",
    "ice skating": "aɪs ˈskeɪtɪŋ",
    "roller skates": "ˈrəʊlə skeɪts",
    "roller skating": "ˈrəʊlə ˈskeɪtɪŋ",
    "pop music": "pɒp ˈmjuːzɪk",
    "rock music": "rɒk ˈmjuːzɪk",
    "table tennis": "ˈteɪbl ˈtenɪs",
    "take a photo": "teɪk ə ˈfəʊtəʊ",
    "tennis racket": "ˈtenɪs ˈrækɪt",
    "board game": "bɔːd ɡeɪm",
    "fire engine": "ˈfaɪər ˈendʒɪn",
    "pop star": "pɒp stɑː(r)",
    "firefighter": "ˈfaɪəfaɪtə(r)",
    "police officer": "pəˈliːs ˈɒfɪsə(r)",
    "look at": "lʊk æt",
    "pick up": "pɪk ʌp",
    "dress up": "dres ʌp",
    "look for": "lʊk fɔː(r)",
    "look after": "lʊk ˈɑːftə(r)",
    "look like": "lʊk laɪk",
    "turn off": "tɜːn ɒf",
    "turn on": "tɜːn ɒn",
    "go to bed": "ɡəʊ tə bed",
    "go to sleep": "ɡəʊ tə sliːp",
    "have got": "hæv ɡɒt",
    "would like": "wʊd laɪk",
    "be called": "biː kɔːld",
}
PHRASE_IPA.update({
    "get dressed": "ɡet drest",
    "get off": "ɡet ɒf",
    "get on": "ɡet ɒn",
    "get undressed": "ɡet ʌnˈdrest",
    "get up": "ɡet ʌp",
    "put on": "pʊt ɒn",
    "take off": "teɪk ɒf",
    "find out": "faɪnd aʊt",
    "go out": "ɡəʊ aʊt",
    "make sure": "meɪk ʃʊə(r)",
    "don't worry": "dəʊnt ˈwʌri",
    "oh dear": "əʊ dɪə(r)",
    "all right": "ɔːl raɪt",
    "a lot of": "ə lɒt ɒv",
    "lots of": "lɒts ɒv",
    "a little": "ə ˈlɪtl",
    "a few": "ə fjuː",
    "a lot": "ə lɒt",
    "at the moment": "æt ðə ˈməʊmənt",
    "how much": "haʊ mʌtʃ",
    "how often": "haʊ ˈɒfn",
    "by myself": "baɪ maɪˈself",
    "by yourself": "baɪ jɔːˈself",
    "how long": "haʊ lɒŋ",
    "of course": "ɒv kɔːs",
    "in front of": "ɪn frʌnt ɒv",
    "next to": "nekst tuː",
    "out of": "aʊt ɒv",
    "how many": "haʊ ˈmeni",
    "how old": "haʊ əʊld",
    "you're welcome": "jɔː ˈwelkəm",
    "stomach ache": "ˈstʌmək eɪk",
    "open/close a file": "ˈəʊpən/kləʊz ə faɪl",
    "win a competition": "wɪn ə ˌkɒmpəˈtɪʃn",
    "catch (a bus)": "kætʃ (ə bʌs)",
    "See you!": "siː juː",
    "Come on!": "kʌm ɒn",
    "Go away!": "ɡəʊ əˈweɪ",
    "If you want!": "ɪf juː wɒnt",
    "In a minute!": "ɪn ə ˈmɪnɪt",
    "No problem!": "nəʊ ˈprɒbləm",
    "Days of the week": "-",
    "Months of the year": "-",
    "The world around us": "-",
    "candy": "ˈkændi",
})


def get_phonetic(word_str):
    """Look up IPA for a word, trying various strategies."""
    # Direct lookup
    if word_str in IPA_DICT:
        return f"/{IPA_DICT[word_str]}/"
    # Phrase lookup
    if word_str in PHRASE_IPA:
        ipa = PHRASE_IPA[word_str]
        if ipa == "-":
            return ""  # category headers, no phonetic needed
        return f"/{ipa}/"
    # Case-insensitive lookup
    lower = word_str.lower()
    if lower in IPA_DICT:
        return f"/{IPA_DICT[lower]}/"
    if lower in PHRASE_IPA:
        ipa = PHRASE_IPA[lower]
        if ipa == "-":
            return ""
        return f"/{ipa}/"
    # Strip parentheses/punctuation and try
    cleaned = re.sub(r'[()!?]', '', word_str).strip()
    if cleaned in IPA_DICT:
        return f"/{IPA_DICT[cleaned]}/"
    if cleaned.lower() in IPA_DICT:
        return f"/{IPA_DICT[cleaned.lower()]}/"
    # For slash variants like "foot/feet"
    if '/' in word_str:
        parts = word_str.split('/')
        ipas = []
        for p in parts:
            p = p.strip()
            if p.lower() in IPA_DICT:
                ipas.append(IPA_DICT[p.lower()])
            else:
                ipas.append(p)
        return f"/{'/'.join(ipas)}/"
    return ""  # empty = not found


def fix_words():
    with open('data/words.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    words = data['words']
    fixed_count = 0
    merged_count = 0
    missing_ipa = []

    for w in words:
        wid = w['id']

        # Step 1: Fix split multi-word entries
        if wid in MERGE_FIXES:
            correct_word, correct_meaning = MERGE_FIXES[wid]
            old_word = w['word']
            w['word'] = correct_word
            w['meaning'] = correct_meaning
            # Update syllables to match new word
            w['syllables'] = [correct_word]
            merged_count += 1

        # Step 2: Fix phonetics
        new_phonetic = get_phonetic(w['word'])
        if new_phonetic:
            w['phonetic'] = new_phonetic
            fixed_count += 1
        else:
            # Keep a cleaned version as fallback
            missing_ipa.append((wid, w['word']))
            # At minimum, format it properly with slashes
            w['phonetic'] = f"/{w['word'].lower()}/"

    # Also fix entries where meaning has (US ...) or (UK ...) annotations
    # that got mangled - clean up meaning field
    for w in words:
        m = w['meaning']
        # Remove leading "(US center) " etc from meaning
        m = re.sub(r'^\(US [^)]+\)\s*', '', m)
        m = re.sub(r'^\(UK [^)]+\)\s*', '', m)
        w['meaning'] = m

    # Update total
    data['total'] = len(words)

    # Write back
    with open('data/words.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Fixed {fixed_count} phonetics")
    print(f"Merged {merged_count} split multi-word entries")
    if missing_ipa:
        print(f"\nMissing IPA for {len(missing_ipa)} words:")
        for wid, word in missing_ipa:
            print(f"  id={wid}: {word}")


if __name__ == '__main__':
    fix_words()
